### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by remy** [leftlogic/leftlogic#9]
Think this got lost somewhere (in my paste to you in IM - rather than you losing it):

Can you change `code` style to:

``` css
code {
  font-size: 1rem;
  background: #DFDFDF;
  display: inline;
  color: #6C5B4D;
  padding: 2px 4px;
  border-radius: 3px;
}
```
